default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: botui8_development

test:
  <<: *default
  database: botui8_test

production:
  <<: *default
  database: botui8_production
  username: botui8
  password: <%= ENV['BOTUI8_DATABASE_PASSWORD'] %>
